### ISSUE TITLE
tacotron2 학습이 제대로 안되는것 같은데 어디가 문제일까요?

### ISSUE THREAD

**Issue by luhavis** [hccho2/Tacotron2-Wavenet-Korean-TTS#4]
설명대로 5만 step+ 학습중입니다
학습이 제대로 되고 있지 않아보이는데 단순히 학습량이 적어서 그런걸까요?

![test-step-000046000-align003](https://user-images.githubusercontent.com/20457282/59889588-02d9fb00-9408-11e9-8a39-e32680304706.png)
![test-step-000046000-align002](https://user-images.githubusercontent.com/20457282/59889589-02d9fb00-9408-11e9-99e6-4798055eb957.png)
![test-step-000046000-align001](https://user-images.githubusercontent.com/20457282/59889590-02d9fb00-9408-11e9-8b3e-8331a6f65bb0.png)
![test-step-000046000-align000](https://user-images.githubusercontent.com/20457282/59889591-03729180-9408-11e9-8fc9-87c1c0174b98.png)

**Comment by hccho2** [comment]
이 것만 가지고는 모르겠네요. data가 충분하지도 모르겠고, 다른 이유가 있을 수도 있고요.

**Comment by luhavis** [comment]
답변 감사합니다. 이것저것 건들여가면서 다시 테스트 해봐야겠네요
